-- Entity Init
create table attendances
(
    late_minutes   integer                                    not null,
    penalty_amount integer                                    not null,
    checked_in_at  timestamp(6) with time zone,
    created_at     timestamp(6) with time zone                not null,
    id             bigint generated by default as identity,
    member_id      bigint,
    session_id     bigint,
    updated_at     timestamp(6) with time zone                not null,
    reason         varchar(255),
    status         enum ('ABSENT','EXCUSED','LATE','PRESENT') not null,
    primary key (id)
);

create table cohort_members
(
    deposit      integer                     not null,
    excuse_count integer                     not null,
    cohort_id    bigint,
    created_at   timestamp(6) with time zone not null,
    id           bigint generated by default as identity,
    member_id    bigint,
    part_id      bigint,
    team_id      bigint,
    updated_at   timestamp(6) with time zone not null,
    primary key (id)
);

create table cohorts
(
    generation integer                     not null unique,
    created_at timestamp(6) with time zone not null,
    id         bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    name       varchar(255)                not null unique,
    primary key (id)
);

create table deposit_histories
(
    amount           integer                             not null,
    balance_after    integer                             not null,
    attendance_id    bigint,
    cohort_member_id bigint,
    created_at       timestamp(6) with time zone         not null,
    id               bigint generated by default as identity,
    updated_at       timestamp(6) with time zone         not null,
    description      varchar(255),
    type             enum ('INITIAL','PENALTY','REFUND') not null,
    primary key (id)
);

create table members
(
    created_at timestamp(6) with time zone            not null,
    id         bigint generated by default as identity,
    updated_at timestamp(6) with time zone            not null,
    login_id   varchar(255)                           not null unique,
    name       varchar(255)                           not null,
    password   varchar(255)                           not null,
    phone      varchar(255)                           not null,
    role       enum ('ADMIN','MEMBER')                not null,
    status     enum ('ACTIVE','INACTIVE','WITHDRAWN') not null,
    primary key (id)
);

create table parts
(
    cohort_id  bigint,
    created_at timestamp(6) with time zone not null,
    id         bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    name       varchar(255)                not null,
    primary key (id),
    constraint uk_part_name_cohort unique (name, cohort_id)
);

create table qrcodes
(
    created_at timestamp(6) with time zone not null,
    id         bigint generated by default as identity,
    session_id bigint,
    expired_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    hash_value varchar(255)                not null unique,
    primary key (id)
);

create table sessions
(
    date       date                                                     not null,
    qr_active  boolean                                                  not null,
    time       time(6)                                                  not null,
    cohort_id  bigint,
    created_at timestamp(6) with time zone                              not null,
    id         bigint generated by default as identity,
    updated_at timestamp(6) with time zone                              not null,
    location   varchar(255)                                             not null,
    title      varchar(255)                                             not null,
    status     enum ('CANCELLED','COMPLETED','IN_PROGRESS','SCHEDULED') not null,
    primary key (id)
);

create table teams
(
    cohort_id  bigint,
    created_at timestamp(6) with time zone not null,
    id         bigint generated by default as identity,
    updated_at timestamp(6) with time zone not null,
    name       varchar(255)                not null,
    primary key (id),
    constraint uk_team_name_cohort unique (name, cohort_id)
);

-- Constraints
alter table if exists attendances
    add constraint FKr7cd1e30648d21vcif5fgfttu
        foreign key (member_id)
            references members;

alter table if exists attendances
    add constraint FK24t12atd4p5tqm2227iqfm11y
        foreign key (session_id)
            references sessions;

alter table if exists cohort_members
    add constraint FKgy8nwcaxd43mdk55eh7o30e4h
        foreign key (cohort_id)
            references cohorts;

alter table if exists cohort_members
    add constraint FKdm4w02066kt47la7349fxqiey
        foreign key (member_id)
            references members;

alter table if exists cohort_members
    add constraint FKp8q1pmua2uhn560v6tvfqsff6
        foreign key (part_id)
            references parts;

alter table if exists cohort_members
    add constraint FKndd5bjexp38o3giatlbb2d1pq
        foreign key (team_id)
            references teams;

alter table if exists deposit_histories
    add constraint FKcx95yqt4vgcpsfwb5k7nucq6e
        foreign key (attendance_id)
            references attendances;

alter table if exists deposit_histories
    add constraint FK7k8wipkmnyv4q4l74t9x7xyti
        foreign key (cohort_member_id)
            references cohort_members;

alter table if exists parts
    add constraint FKqggkgdvix1prgvvp4jg71klpw
        foreign key (cohort_id)
            references cohorts;

alter table if exists qrcodes
    add constraint FK216x141spktultmrqjcjfj9gj
        foreign key (session_id)
            references sessions;

alter table if exists sessions
    add constraint FKrjc4kncf2pfi2com44qh6930s
        foreign key (cohort_id)
            references cohorts;

alter table if exists teams
    add constraint FK1rwg7avaj5byag296usau9e4s
        foreign key (cohort_id)
            references cohorts;